language: python
python:
    - "2.7"
install: 
    - "pip install pep8"
    - "pip install pylint"
    - "pip install coverage"
    - "pip install coveralls"
script: 
    - "pep8 ./scripts/* virtTrinity/"
    - "pylint ./scripts/* virtTrinity/ --reports=n --disable=W,R,C"
    - "coverage run --source=virtTrinity,scripts/virt-trinity setup.py test"
after_success:
    coveralls
