#!/usr/bin/env python

from virtTrinity import virsh
from virtTrinity import utils

def iter_command(command):
    """Iterate through all possible combinated command lines
    for a virsh sub command *command*.

    :param command: A virsh sub command to be iterated.
    :type command: str.
    """
    vsh = virsh.Virsh()
    cmdline_generator = vsh.cmdline_generator(command)
    for counter, cmd_line in enumerate(cmdline_generator):
        print counter,
        result = utils.run(cmd_line, timeout=1.0)
        result.pprint()

def fuzzer():
    """A fuzzer continuously run random virsh commands.
    """
    vsh = virsh.Virsh()
    while True:
        cmd_line = vsh.get_random_cmdline()
        result = utils.run(cmd_line, timeout=1.0)
        result.pprint()

if __name__ == '__main__':
    fuzzer()
